### ISSUE TITLE
Ping peer continuously closed channel

### ISSUE THREAD

**Issue by KaloyanTanev** [ObolNetwork/charon#3053]
# 🐞 Bug Report

On command `alpha test peers` sometimes during peer pinging there is panic because of a closed channel. This is caused because we close the channel `testResCh` in `peerPingLoadTest` function and try to send data on it afterwards in `pingPeerContinuously`.

## 🔬 Minimal Reproduction

Run ping peer tests with 2 or more peers. Not guaranteed to error every time as it is dependant on async calls.

## 🔥 Error

```
panic: send on closed channel

goroutine 303 [running]:
github.com/obolnetwork/charon/cmd.pingPeerContinuously({0x101da42a0, 0x140005c0dc0}, {0x101db5960, 0x140000ec300}, {{0x14000880090, 0x27}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
        github.com/obolnetwork/charon/cmd/testpeers.go:216 +0x6c
created by github.com/obolnetwork/charon/cmd.peerPingLoadTest in goroutine 194
        github.com/obolnetwork/charon/cmd/testpeers.go:545 +0x39c
```

**Comment by KaloyanTanev** [comment]
Fixed by #3054
