### ISSUE TITLE
Proxy event stream from beacon node

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#688]
## Problem to be solved

Teku complains that it can't communicate with the BN event stream

```
teku_1        | 2022-06-09 14:49:32.587 ERROR - Validator   *** Error while connecting to beacon node event stream
teku_1        | java.net.SocketTimeoutException: timeout
teku_1        | at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143) ~[okio-jvm-2.8.0.jar:?]
teku_1        | at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162) ~[okio-jvm-2.8.0.jar:?]
teku_1        | at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335) ~[okio-jvm-2.8.0.jar:?]
teku_1        | at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427) ~[okio-jvm-2.8.0.jar:?]
```

## Proposed solution

Proxy the event stream from BN to validator-api charon component. Mutate objects as required to fool the downstream validator as to its private key. 

### Out of Scope

Testing whether we can use charon issued events on this event stream to force/prompt the VC into behaviour that could help us (e.g. tricking it into asking for a block early with a fork updated event)

**Comment by corverroos** [comment]
At this point on teku does events, and it only asks for "slot"/"head" events, so we do not need to mutate data.
